CREATE TABLE CUSTOMER (
C_ID NUMBER PRIMARY KEY,
C_FIRST_NAME VARCHAR2 (20),
C_LAST_NAME VARCHAR2 (20),
C_USER_NAME VARCHAR2 (20),
C_PASSWORD VARCHAR2 (20),
ACCOUNT_NUMBER NUMBER);
ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ACCOUNT
FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER);

CREATE SEQUENCE CSEQ
START WITH 1001;

CREATE TABLE OFFER (
OFFER_ID NUMBER PRIMARY KEY,
C_ID NUMBER,
CAR_ID NUMBER);
ALTER TABLE OFFER
ADD CONSTRAINT FK_OFFER_CUSTOMER
FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID);
ALTER TABLE OFFER
ADD CONSTRAINT FK_OFFER_CAR
FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID);

CREATE SEQUENCE OSEQ
START WITH 1001;


CREATE TABLE EMPLOYEE (
E_ID NUMBER PRIMARY KEY,
E_FIRST_NAME VARCHAR2 (20),
E_LAST_NAME VARCHAR2 (20),
E_USER_NAME VARCHAR2 (20),
E_PASSWORD VARCHAR2 (20));

CREATE TABLE CAR (
CAR_ID NUMBER PRIMARY KEY,
CAR_MAKE VARCHAR2 (20),
CAR_MODEL VARCHAR2 (20),
CAR_COLOR VARCHAR2 (20),
CAR_YEAR NUMBER,
CAR_PRICE NUMBER,
OFFERS NUMBER,
CAR_SOLD VARCHAR2 (5));

CREATE SEQUENCE CARSEQ;


CREATE TABLE ACCOUNT (
ACCOUNT_NUMBER NUMBER PRIMARY KEY,
DEPOSITS NUMBER,
BALANCE NUMBER);
